---
os: osx
osx_image: xcode10.2

install:
  - pip3 install testinfra ansible ansible-lint yamllint
  - ansible-galaxy install -r tests/requirements.yml
  - mv tests/_ansible.cfg ./ansible.cfg
  - mv tests/_.ansible-lint ./.ansible-lint

script:
  - yamllint .
  - ansible-lint .
  - ansible-playbook tests/prepare.yml -vv
  - ansible-playbook tests/provision.yml -vvv
  - py.test -v tests/test.py
